version: "3.7"

volumes:
    postgres_data:

services:
    postgres:
        image: postgres:14.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init-event-store.sql:/docker-entrypoint-initdb.d/init-event-store.sql
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password123
        command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
